version: '3'
services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 